name: Deploy to EC2 Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./CI-Backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and push Frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./CI-Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.BACKEND_SSH_PRIVATE_KEY }}
            ${{ secrets.FRONTEND_SSH_PRIVATE_KEY }}

      - name: Add Backend Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.89.123.214 >> ~/.ssh/known_hosts

      - name: Deploy to Backend EC2
        run: |
          # Copy .env file to backend server
          scp -o StrictHostKeyChecking=no ./CI-Backend/.env ec2-user@3.89.123.214:/home/ec2-user/backend.env

          ssh -o StrictHostKeyChecking=no ec2-user@3.89.123.214 << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d -p 4000:4000 --name backend \
              --env-file /home/ec2-user/backend.env \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest
            sudo nginx -t
            sudo systemctl reload nginx
          EOF

      - name: Add Frontend Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 34.238.152.78 >> ~/.ssh/known_hosts

      - name: Deploy to Frontend EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@34.238.152.78 << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 3000:3000 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            sudo nginx -t
            sudo systemctl reload nginx
          EOF
