name: CI/CD Pipeline - Deploy Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
            # Build & push backend image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          

      # Build & push frontend image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
           # Deploy backend container
      - name: Deploy Backend on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.BACKEND_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.BACKEND_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/backend:latest




             # Deploy frontend container and restart nginx reverse proxy
      - name: Deploy Frontend and Restart NGINX
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.FRONTEND_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.FRONTEND_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/frontend:latest

             # Reload nginx to apply reverse proxy config changes if needed
            sudo systemctl reload nginx
